version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: devops/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../app:/app/app
    env_file: 
      - .env
    depends_on:
      - postgres
    command: >
      sh -c "flask run --host=0.0.0.0"

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flaskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
