version: "3.9"

services:
  flask-api:
    build:
      context: ../
      dockerfile: ./devops/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
      - mongo
    volumes:
      - ../app:/app/app

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
