
services:
  ms-usuarios:
    build:
      context: ../ms-usuarios
      dockerfile: Dockerfile  
    ports:
      - "8000:80"
    env_file:
    - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - JWT_SECRET=${SECRET_KEY}
  
  db-usuarios:
    image: postgres:13
    env_file:
    - .env
    volumes:
      - pgdata-usuarios:/var/lib/postgresql/data

volumes:
  pgdata-usuarios: